### ISSUE TITLE
Error in open.connection(con, "rb") : HTTP error 404.

### ISSUE THREAD

**Issue by gusbruschi13** [r-music/vagalumeR#2]
Olá, tudo bem ?

Eu tentei puxar algumas informações de um grupo de artistas, e surgiu o erro abaixo.

```
lista_artistas <- c("dilsinho","ferrugem",
                    "sorriso-maroto","turma-do-pagode",
                    "thiaguinho","revelacao",
                    "exaltasamba","raça-negra",
                    "belo","xande-de-pilares",
                    "pericles","so-pra-contrariar",
                    "molejo","alexandre-pires",
                    "art-popular","os-travessos")

info_artistas <- as.data.frame(map(lista_artistas, artistInfo))

Error in open.connection(con, "rb") : HTTP error 404.
```

**Comment by brunaw** [comment]
Olá, @gusbruschi13. Seu problema é que alguns artistas não estão com o nome da mesma forma que está escrito na API do Vagalume. Eu encontrei 3 que não bateram e troquei para:

revelacao --> grupo-revelacao
exaltasamba --> exalta-samba
raça-negra -->  raca-negra

O código funcionando é:

```
library(vagalumeR)
library(tidyverse)
lista_artistas <- c("dilsinho","ferrugem",
                    "sorriso-maroto","turma-do-pagode",
                    "thiaguinho","grupo-revelacao",
                    "exalta-samba","raca-negra",
                    "belo","xande-de-pilares",
                    "pericles","so-pra-contrariar",
                    "molejo","alexandre-pires",
                    "art-popular","os-travessos")

info_artistas <- as.data.frame(map(lista_artistas, artistInfo))
```
Nem sempre é óbvio como os nomes dos artistas devem ser escritos para funcionar. Quando acontecer isso, você pode conferir no site do vagalume, pesquisando o nome do artista: https://www.vagalume.com.br/  e vendo como ele está declarado na URL. Por exemplo, o Raça Negra seria "raca-negra", como está aqui: https://www.vagalume.com.br/raca-negra/ :)

**Comment by gusbruschi13** [comment]
@brunaw 

Verifiquei aqui e vi que é isso mesmo.
Obrigado pelo ajuda.
